export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE'

export const EDIT_MOVIE_REQUEST = 'EDIT_MOVIE_REQUEST'
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS'
export const EDIT_MOVIE_FAILURE = 'EDIT_MOVIE_FAILURE'

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE'

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
export const GET_MOVIE_FAILURE = 'GET_MOVIES'


