export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST'
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE'

export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST'
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE'

export const EDIT_BOOK_REQUEST = 'EDIT_BOOK_REQUEST'
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS'
export const EDIT_BOOK_FAILURE = 'EDIT_BOOK_FAILURE'

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE'

export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST'
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS'
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE'
